
alias dc='docker-compose'
alias k="kubectl"
alias kl="k get all"
alias kn="kubens"
alias dm="docker-machine"
alias d="docker"

ZSH_DISABLE_COMPFIX=true
export LC_ALL=en_US.UTF-8
export PATH=$HOME/bin:/usr/local/sbin:$HOME/Library/Python/3.7/bin:/usr/local/flutter/bin:$HOME/.local/bin:/Applications/Postgres.app/Contents/Versions/11/bin:$PATH
export KUBECONFIG=~/.kube/public.dev

export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="sunrise"

plugins=(git command-time zsh-autosuggestions zsh-syntax-highlighting fzf)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs vcs custom_command_time time)
source $ZSH/oh-my-zsh.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/google-cloud-sdk/path.zsh.inc' ]; then . '/usr/local/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/google-cloud-sdk/completion.zsh.inc' ]; then . '/usr/local/google-cloud-sdk/completion.zsh.inc'; fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
