alias watch='watch '
alias dc='docker-compose'
alias k="kubectl"
alias kl="k get all"
alias dm="docker-machine"
alias d="docker"

ZSH_DISABLE_COMPFIX=true
export NODE_OPTIONS=--max-old-space-size=6144
export LC_ALL=en_US.UTF-8
export PATH=$HOME/bin:$HOME/flutter/bin:$(go env GOPATH)/bin:/usr/local/sbin:$HOME/Library/Python/3.7/bin:/usr/local/flutter/bin:$HOME/.local/bin:/Applications/Postgres.app/Contents/Versions/11/bin:$HOME/.pub-cache/bin:$PATH

export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="sunrise"

plugins=(git command-time zsh-autosuggestions zsh-syntax-highlighting fzf zsh-completions)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs vcs custom_command_time time)
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

